### ISSUE TITLE
Installing POPF on MacOS (Mojave)

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [LCAS/popf#2]
@marc-hanheide (and team): Thank you for providing the repo.
Has anyone built this on a Mac?  CMake is not able to find the COIN-OR libraries that I installed using Homebrew.  Each of them has a pkgconfig folder but no cmake files.:

    -- Could NOT find Clp (missing: CLP_INCLUDES)
    -- Could NOT find CoinUtils (missing: COINUTILS_INCLUDES)
    -- Could NOT find Cbc (missing: CBC_INCLUDES)
    -- Could NOT find Cgl (missing: CGL_INCLUDES)
    -- Could NOT find OSI (missing: OSI_INCLUDES)

**Comment by marc-hanheide** [comment]
never attempted this and not tried any of it for a long time I'm afraid. And this is also quite outdated and not actively maintained. Maybe better to get in touch with the original authors.

**Comment by Napoleon-BlownApart** [comment]
Hi Marc, for what it's worth, I've forked the repository to my own account and made all the necessary changes so it now builds and runs.
I've tested the parser on some IPC domains, but I haven't tested any actual planning.  If you can help me here by suggesting a suitable domain/problem from the IPC problem list, I would be grateful.

**Comment by marc-hanheide** [comment]
👍 

Sorry, I only used popf for some academic problems with students (and a long time ago). I really am not the to-go-to guy. Wish I could offer something better ;-)

**Comment by Napoleon-BlownApart** [comment]
Sure, no problem Marc and thanks again for hosting this repo.
I've tested my forked version for the Mac using a Blocks World problem from the IPC sample problem list as well as the MetricVehicle example from Fox/Long's PDDL2.1 definition, both work fine.
